export const queryKeys = {
  products: ["products"] as const,
  productsFiltered: (params: Record<string, unknown>) => ["products", params] as const,
  product: (id: string) => ["products", id] as const,
  productSlug: (slug: string) => ["products", "slug", slug] as const,
  categories: ["categories"] as const,
  cart: ["cart"] as const,
  profile: ["profile"] as const,
  orders: ["orders"] as const,
  order: (id: string) => ["orders", id] as const,
  allOrders: ["allOrders"] as const,
  featuredProducts: ["featuredProducts"] as const,
  newArrivals: ["newArrivals"] as const,
  offers: ["offers"] as const,
  offer: (id: string) => ["offers", id] as const,
  coupons: ["coupons"] as const,
  coupon: (id: string) => ["coupons", id] as const,
  customers: ["customers"] as const,
  customer: (id: string) => ["customers", id] as const,
  customerOrders: (id: string) => ["customers", id, "orders"] as const,
  addresses: ["addresses"] as const,
  wishlist: ["wishlist"] as const,
  reviews: (productId: string) => ["reviews", productId] as const,
  adminOrders: (status?: string) => ["adminOrders", status ?? "all"] as const,
  adminCustomers: (q?: string) => ["adminCustomers", q ?? ""] as const,
  adminCoupons: ["adminCoupons"] as const,
  adminReturns: (status?: string) => ["adminReturns", status ?? "all"] as const,
  adminAdmins: ["adminAdmins"] as const,
  adminAuditLogs: ["adminAuditLogs"] as const,
  adminRevenue: ["adminRevenue"] as const,
  adminOrdersByStatus: ["adminOrdersByStatus"] as const,
  adminTopProducts: ["adminTopProducts"] as const,
  adminRecentOrders: ["adminRecentOrders"] as const,
  adminLowStock: ["adminLowStock"] as const,
};
